name: Mise à jour quotidienne du README

on:
  schedule:
    # Planification : tous les jours à minuit (UTC)
    - cron: "0 0 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configuration de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Remplacez par votre version de Node.js si nécessaire

      # Étape 3 : Installer les dépendances (si nécessaires)
      - name: Install dependencies
        run: npm install

      # Étape 4 : Exécuter le script de mise à jour
      - name: Mettre à jour le README
        run: node update-readme.js

      # Étape 5 : Ajouter, commit et push les modifications
      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Mise à jour automatique de la date : $(date +'%d/%m/%Y')"
          git push
