name: Update README daily

on:
  schedule:
    - cron: "0 23 * * *" # Exécute tous les jours à 23h UTC (minuit à Tunis)
  workflow_dispatch: # Permet l'exécution manuelle

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Set up Git config
        run: |
          git config --global user.name "Martialdepaul"
          git config --global user.email "bourangoneulomimartialdepaul@gmail.com"

      - name: Install dependencies
        run: npm install

      - name: Update README date
        run: node update-readme.js

      - name: Commit and Push changes
        run: |
          git add README.md
          git commit -m "docs: 📅 mise à jour quotidienne $(TZ='Africa/Tunis' date +'%d/%m/%Y') [bot]" || exit 0
          git push
