name: Update README daily

on:
  schedule:
    - cron: "0 0 * * *" # Exécute tous les jours à minuit

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Git configuration
      - name: Set up Git config
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      # 3. Pull latest changes from the remote (to prevent conflicts)
      - name: Pull latest changes from the remote
        run: |
          git pull origin main --rebase

      # 4. Run the script to update the README
      - name: Update README date
        run: |
          node update-readme.js

      # 5. Commit and push changes
      - name: Commit and Push changes
        run: |
          git add README.md
          git commit -m "Mise à jour quotidienne du README"
          git push origin main
