name: Update README daily

on:
  schedule:
    - cron: "0 22 * * *" # Exécute tous les jours à 22h UTC (23h UTC+1)

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git config
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Pull latest changes
        run: |
          git fetch origin main
          git reset --hard origin/main

      - name: Debug date
        run: date

      - name: Update README date
        run: |
          node update-readme.js || echo "Erreur dans le script Node.js"

      - name: Debug file changes
        run: git diff README.md || echo "Aucun changement détecté dans README.md"

      - name: Commit and Push changes
        run: |
          git add README.md
          git commit -m "Mise à jour quotidienne du README" || echo "Aucun changement à valider."
          git push origin main --force
